--This loads all of the new prefabs.

PrefabFiles = {
	"winnie",
	"winnie_staff",
	"winnie_sheep",
	"kettle",
	"cauldron",
	"refiner",

	-- Dummy prefab for morgue trickery.
	"staticdummy",

	-- Stuff in progress.
	--------------------

	"pineapple_bush",
	"pineapple",
	"cloudblob",
	"alchemy_potions",
	"potion_tunnel_mound",
	"colored_corn",
	"gemcorn",
	"gnome_wilson",
	"gnome_decor",
	"gnome_plot",
	"cloud_wall",
	"chest_sky",
	"live_gnome",
	"rubber_armor",
	"shopkeeper_umbrella",
	"rhinoman",

	--"rubber_cap",
	--"rubber_ducky",
	--"thundertree_sapling",

	------------------------------

	-- Bosses and their drops.
	"superconductor",
	"radiant_orb",

	"bean_giant",
	"bean_brain",
	"super_beans",

	"octocopter",

	------------------------------

	"ua_cave",
	"cloudrealm",
	"cloud_mist",
	"cloud_lightning",
	"shopkeeper",
	"shopkeeper_spawner",
	"sheep",	
	"vine",
	"bee_marshmallow",
	"hive_marshmallow",	
	"candy_fruit",
	"marshmallow",	
	"skyflies",
	"flying_fish",	
	"goose",	
	"longbill",	
	"crystal_spire",	
	"skyflower",
	"skyflower_petals",
	"beanstalk",
	"beanstalk_exit",
	"thunder_tree",	
	"balloon_hound",
	"beanlet_shell",
	"cloud_algae",
	"cloud_algae_fragment",
	"cloud_coral",
	"cloud_coral_fragment",
	"alien",
	"greenbean",
	"jellyshroom",
	"refiner",
	"scarecrow",	
	"beanstalk_chunk",	
	"beanstalk_sapling",	
	"cloud_cotton",		
	"cloud_turf",	
	"cloud_bush",
	"cloudcrag",	
	"golden_egg",
	"wind_axe",
	"duckraptor",		
	"lionblob",
	"owl",
	"crystal_relic",
	"crystal_fragment_relic",
	"crystal_fragment_spire",
	"cotton_vest",
	"research_lectern",	
	"beanstalk_wall",
	"smores",
	"weather_machine",	
	"skytrap",	
	"crystal_lamp",		
	"cotton_candy",	
	"ball_lightning",
	"magnet",
	"cotton_candy",
	"rubber",
	"crystal_fragment_black",
	"crystal_fragment_white",
	"crystal_fragment_water",
	"crystal_fragment_quartz",
	"golden_sunflower",
	"golden_sunflower_seeds",
	"gustflower",
	"gustflower_seeds",		
	"beanlet_zealot",		
	"crystal_black",
	"crystal_white",	
	"beanlet",		
	"crystal_water",
	"crystal_quartz",			
	"cotton_hat",	
	"whirlwind",
	"cumulostone",
	"dragonblood_tree",
	"dragonblood_sap",
	"crystal_light",
	"crystal_fragment_light",
	"cauldron",
	"cloud_fruit_tree",
	"cloud_fruit",
	"crystal_wall",
	"beanstalk_wall",
	"golden_rose",
	"golden_petals",
	"tea",
	"tea_leaves",
	"tea_bush",
	"kettle",
	"ua_staves",
	"weavernest",
	"weaver_bird",
	"package",
	"refined_black_crystal",
	"refined_white_crystal",
	"dragonblood_log",
	"thunder_log",
	"mushroom_hat",
	"sheepherd",
	"cloud_jelly",
	"gummybear",
	"gummybear_den",
	"thunderboards",
	"ambrosia",
	"beanlet_armor",
	"beanlet_hut",
	"campfirefire_dragon",
	"thunder_pinecone",
	"ua_cookedfoods",
	"magic_beans",

	--Stuff not started.
	--------------------

	--"beanlet_lamp",
	--"crystal_moss",	
	--"crystal_crown",
	--"cloud_bomb",	
	--"golden_amulet",
	--"kite",
	--"antlion",	
	--"cheshire",
	--"chimera",
	--'bird_paradise',
	--"rainbowcoon",	
	--"grabber",
	--"minicopter"
	--"golden_golem",	
	--"monolith",	
	--"mantaspawner",
	--"crystal_armor",
	--"crystal_axe",
	--"sky_lemur",
	--"quartz_torch",
	--"jellyshroomfish",
	--"manta",
	--"manta_baby",
	--"manta_leather",
	
}

-- The return statement is just for if this file is used externally, at
-- least for now it's the PrefabFiles variable that matters.
return PrefabFiles
