---------------------------------------

-- Winnie

WINNIE.HEALTH = 100
WINNIE.SANITY = 80
WINNIE.HUNGER = 100

WINNIE.MEAT_PENALTY_HEALTH = -15
WINNIE.MEAT_PENALTY_SANITY = -40

WINNIE.MEAT_PENALTY_NAUGHTY = 5

WINNIE.VEGGIE_BONUS_HEALTH = 1
WINNIE.VEGGIE_BONUS_SANITY = 5
WINNIE.VEGGIE_BONUS_HUNGER = 10

WINNIE.VEGGIE_BONUS_NAUGHTY = -2

WINNIE.DAMAGE_MULTIPLIER = 0.35

WINNIE.WALK_SPEED = TUNING.WILSON_WALK_SPEED * 1.1 
WINNIE.RUN_SPEED = TUNING.WILSON_RUN_SPEED * 1.1

WINNIE.HEALTH_PERCENT = 60

WINNIE.SANITY_BONUS_CAP = 10
WINNIE.NAUGHTY_BONUS = 0.5
WINNIE.PROJECTILE_MULT = 0.3

WINNIE.VEGGIE_RESIST = 0.2

-- Loot and Prefabs

WINNIE.PREFABS = {
    "sheep",
    "winnie_staff",
    "winnie_flute",
}

WINNIE.STARTING_INV = {
    "winnie_staff",
    "winnie_flute"
}

WINNIE.PERMANENT_ITEMS = {
    "winnie_staff",
    "winnie_flute",
}

---------------------------------------

--  Winston

WINSTON.HEALTH = 300
WINSTON.SANITY = 80
WINSTON.HUNGER = 300

WINSTON.WALK_SPEED = TUNING.WILSON_WALK_SPEED * 0.8
WINSTON.RUN_SPEED = TUNING.WILSON_RUN_SPEED * 0.8

WINSTON.DAMAGE_MULTIPLIER = 0.8

-- Loot and Prefabs

WINSTON.PREFABS = {
    "winston_tool",
}

WINSTON.STARTING_INV = {
    "winston_tool",
}

WINSTON.PERMANENT_ITEMS = {
    "winston_tool",
}

---------------------------------------