HOTBEVERAGE.INHERENT_INSULATION = 60
HOTBEVERAGE.SPOILED_PREFAB = "spoiled_food"

--[[
-- The following refers to *brewed* tea.
--]]
HOTBEVERAGE.TEA.HEAT_CAPACITY = 0.15
HOTBEVERAGE.TEA.PERISH_TIME = 1.5*TUNING.TOTAL_DAY_TIME
